url: https://www.nullsum.uk
baseurl: 

# Site settings
title: NULL SUM
email: hello@nullsum.uk
phone: 0870 875 2029
description: "NULL SUM UK Based DevOps & SRE contract consultancy."
company: Null Sum Ltd
companyNo: 14454244

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/company/nullsum
  - title: github
    url: https://github.com/nullsumltd

# Postal address (add as many lines as necessary)
address:
  - line: Unit 36
  - line: Silk Mill Industrial Estate
  - line: Brook Street
  - line: Tring
  - line: HP23 5EF

# Build settings
markdown: kramdown
permalink: pretty